
//! geodb-wasm — WebAssembly bindings for geodb-core
//!
//! This crate exposes a small, ergonomic JS/WASM API built on top of
//! `geodb-core`. It embeds a compact, serialized database in the WASM
//! binary and provides search helpers callable from JavaScript.
//!
//! What it provides
//! ----------------
//! - Automatic initialization on module load (via `#[wasm_bindgen(start)]`)
//! - Basic queries: `get_country_count()`, `get_country_name(iso2)`
//! - Search helpers returning JSON-serializable objects:
//!   - `search_countries_by_phone("+49")`
//!   - `search_state_substring("bavar")`
//!   - `search_city_substring("berlin")`
//!   - `smart_search("us" | "+1" | "berlin" | ...)`
//!
//! Quick start (browser)
//! ---------------------
//! ```javascript
//! import init, { get_country_count, smart_search } from 'geodb-wasm';
//!
//! async function main() {
//!   await init(); // initializes the embedded DB
//!   console.log('Countries:', get_country_count());
//!
//!   const results = smart_search('berlin');
//!   // results is a JSON array of mixed kinds: country/state/city
//!   console.log(results);
//! }
//! main();
//! ```
//!
//! Quick start (Node.js + bundler)
//! -------------------------------
//! ```javascript
//! import init, { search_countries_by_phone } from 'geodb-wasm';
//!
//! (async () => {
//!   await init();
//!   console.log(search_countries_by_phone('+1'));
//! })();
//! ```
//!
//! Notes
//! -----
//! - The WASM build embeds a prebuilt binary database (`geodb.standard.bin`).
//!   If you customize data, rebuild the crate to refresh the embedded bytes.
//! - All exported functions are `wasm_bindgen` bindings and return plain types
//!   or `JsValue` containing JSON-serializable arrays/objects.
//! - See the `dist/` folder for a Trunk-based demo setup.
#[cfg(target_arch = "wasm32")]
use flate2::read::GzDecoder;
#[cfg(target_arch = "wasm32")]
use std::io::Read;

use std::sync::OnceLock;
use wasm_bindgen::prelude::*;

// Core Imports
use geodb_core::api::{CityView, CountryView, StateView};
use geodb_core::prelude::*; // Imports DefaultGeoDb, GeoSearch, etc.
use serde::Serialize;
use serde_wasm_bindgen::to_value;

// 1. Embed the Database
// We expect a file named 'geodb.bin' (or whatever standard name you choose) to exist.
// The builder should have created this.
// Use the absolute path calculated by build.rs
// -----------------------------------------------------------------------------
// DATA EMBEDDING (The Feature Matrix)
// -----------------------------------------------------------------------------
// We select the correct binary file based on the compilation features.
// Note: These files must be generated by 'geodb-cli build' before compiling WASM.

// 1. Legacy Nested + Compressed (The default for education)
// -----------------------------------------------------------------------------
// DATA EMBEDDING MATRIX
// -----------------------------------------------------------------------------

#[cfg(all(target_arch = "wasm32", not(docsrs)))]
static EMBEDDED_DB: &[u8] = include_bytes!(env!("GEO_DB_PATH"));

// Stub for docs / non-wasm targets
#[cfg(any(docsrs, not(target_arch = "wasm32")))]
static EMBEDDED_DB: &[u8] = b"";

// 2. Static Instance
static DB: OnceLock<DefaultGeoDb> = OnceLock::new();

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
    web_sys::console::log_1(&"Initializing GeoDB WASM module...".into());

    DB.get_or_init(|| {
        // ... decompression logic ...
        let mut decoder = GzDecoder::new(EMBEDDED_DB);
        let mut decompressed = Vec::new();
        decoder
            .read_to_end(&mut decompressed)
            .expect("Decompression failed");
        web_sys::console::log_1(&DefaultGeoDb::default_dataset_filename().into());
        // ... deserialization ...
        let db: DefaultGeoDb = bincode::deserialize(&decompressed).expect("Deserialize failed");

        // Log stats via Trait
        let stats = db.stats();
        web_sys::console::log_1(&format!("✓ Loaded {} countries", stats.countries).into());

        db
    });
}

/* --------------------------------------------------------------------------
   Basic Queries
-------------------------------------------------------------------------- */

#[wasm_bindgen]
pub fn get_country_count() -> usize {
    match DB.get() {
        Some(db) => db.countries().len(),
        None => 0,
    }
}

#[wasm_bindgen]
pub fn get_country_name(iso2: &str) -> Option<String> {
    match DB.get() {
        Some(db) => db.find_country_by_iso2(iso2).map(|c| c.name().to_string()),
        None => None,
    }
}

/* --------------------------------------------------------------------------
   Country Search
-------------------------------------------------------------------------- */

/// Searches for countries by their international phone code.
///
/// This function takes a string that can be a full phone number or just the
/// country code prefix (e.g., "+1", "49"). It strips leading `+` characters
/// and whitespace before performing the search.
///
/// # Arguments
///
/// * `phone` - A string containing the phone code to search for. It can
///   optionally be prefixed with `+`.
///
/// # Returns
///
/// A `JsValue` representing a JSON array of `CountryView` objects that match
/// the phone code. If multiple countries share the same code (e.g., USA and
/// Canada with "+1"), all will be returned. Returns `JsValue::NULL` if the
/// database is not initialized.
#[wasm_bindgen]
pub fn search_countries_by_phone(phone: &str) -> JsValue {
    let code = phone.trim().trim_start_matches('+');
    match DB.get() {
        Some(db) => {
            let _ = db
                .find_countries_by_phone_code(code)
                .iter()
                .map(|c| CountryView(c))
                .collect::<Vec<_>>();
            let items: Vec<_> = db
                .find_countries_by_phone_code(code)
                .iter()
                .map(|c| CountryView(c))
                .collect();
            to_value(&items).unwrap_or(JsValue::NULL)
        }
        None => JsValue::NULL,
    }
}

/* --------------------------------------------------------------------------
   State Search
-------------------------------------------------------------------------- */

/// Searches for states by a substring of their name.
///
/// This function performs a case-insensitive search for states where the provided
/// substring appears anywhere in the state's name.
///
/// # Arguments
///
/// * `substr` - The substring to search for within state names (e.g., "bava" for Bavaria).
///
/// # Returns
///
/// A `JsValue` representing a JSON array of `StateView` objects that match the
/// search query. Each object includes details about the state and its parent
/// country. Returns `JsValue::NULL` if the database is not initialized.
#[wasm_bindgen]
pub fn search_state_substring(substr: &str) -> JsValue {
    let out: Option<Vec<_>> = DB.get().map(|db| {
        db.find_states_by_substring(substr)
            .into_iter()
            .map(|(state, country)| StateView { country, state })
            .collect()
    });
    to_value(&out).unwrap_or(JsValue::NULL)
}

/* --------------------------------------------------------------------------
   City Search
-------------------------------------------------------------------------- */

/// Searches for cities by a substring of their name.
///
/// This function performs a case-insensitive search for cities where the provided
/// substring appears anywhere in the city's name.
///
/// # Arguments
///
/// * `substr` - The substring to search for within city names (e.g., "berlin").
///
/// # Returns
///
/// A `JsValue` representing a JSON array of `CityView` objects that match the
/// search query. Each object includes details about the city, its state, and
/// its country. Returns `JsValue::NULL` if the database is not initialized.
#[wasm_bindgen]
pub fn search_city_substring(substr: &str) -> JsValue {
    let out: Option<Vec<_>> = DB.get().map(|db| {
        db.find_cities_by_substring(substr)
            .into_iter()
            .map(|(city, state, country)| CityView {
                country,
                state,
                city,
            })
            .collect()
    });
    to_value(&out).unwrap_or(JsValue::NULL)
}

/* --------------------------------------------------------------------------
   Smart Search (country + state + city + phone)
-------------------------------------------------------------------------- */

/// Performs a versatile search across countries, states, and cities.
///
/// This function intelligently interprets the query string to search for:
/// - Country names, ISO codes, or phone codes.
/// - State names or substrings.
/// - City names or substrings.
///
/// It returns a heterogeneous array of matching items, which can include
/// countries, states, and cities.
///
/// # Arguments
///
/// * `query` - The search string. This can be a country ISO code (e.g., "US"),
///   a phone code (e.g., "+1"), or a substring of a country, state, or city
///   name (e.g., "berlin").
///
/// # Returns
///
/// A `JsValue` representing a JSON array of search results. The array may
/// contain a mix of `CountryView`, `StateView`, and `CityView` objects.
/// Returns an empty array if the database is not initialized or if no
/// results are found.
#[wasm_bindgen]
pub fn smart_search(query: &str) -> JsValue {
    let array = match DB.get() {
        Some(db) => {
            let hits = db.smart_search(query);

            // Map to JS serializable wrappers while preserving order
            let array = js_sys::Array::new();
            for hit in hits {
                let v = match hit.item {
                    SmartItem::Country(c) => to_value(&CountryView(c)),
                    SmartItem::State { country, state } => to_value(&StateView { country, state }),
                    SmartItem::City {
                        country,
                        state,
                        city,
                    } => to_value(&CityView {
                        country,
                        state,
                        city,
                    }),
                }
                .unwrap_or(JsValue::NULL);
                array.push(&v);
            }
            array
        }
        None => js_sys::Array::new(),
    };

    array.into()
}

/// Retrieves statistics about the loaded database.
///
/// This function returns a summary of the data contained within the embedded
/// GeoDB instance, such as the total number of countries, states, and cities.
///
/// # Returns
///
/// A `JsValue` representing a JSON object with database statistics, or
/// `JsValue::NULL` if the database has not been initialized. The object
/// structure is similar to:
///
/// ```json
/// {
///   "countries": 250,
///   "states": 4993,
///   "cities": 154933
/// }
/// ```
#[wasm_bindgen]
pub fn get_stats() -> JsValue {
    let stats = DB.get().map(|db| db.stats());
    to_value(&stats).unwrap_or(JsValue::NULL)
}

/// Retrieves metadata about the compiled WASM module and the embedded database.
///
/// This function provides insights into how the module was built, including the
/// specific database file that was embedded, its size, and the compile-time
/// features that were enabled. This is useful for debugging and understanding
/// which version of the data model is active.
///
/// # Returns
///
/// A `JsValue` representing a JSON object with build details. On failure (e.g.,
/// serialization error), it returns `JsValue::NULL`. The object has the
/// following structure:
///
/// ```json
/// {
///   "filename": "geodb.nested.bin",
///   "size_bytes": 123456,
///   "architecture": "nested",
///   "features": {
///     "legacy_model": true,
///     "compact": false,
///     "search_blobs": false
///   }
/// }
/// ```
#[wasm_bindgen]
pub fn get_build_info() -> JsValue {
    #[derive(Serialize)]
    struct Features {
        legacy_model: bool,
        compact: bool,
        search_blobs: bool,
    }

    #[derive(Serialize)]
    struct BuildInfo {
        filename: String,
        size_bytes: usize,
        architecture: &'static str,
        features: Features,
    }
    let arch = if cfg!(feature = "legacy_model") {
        "nested"
    } else {
        "flat"
    };
    let is_compact = cfg!(feature = "compact");
    let has_blobs = cfg!(feature = "search_blobs");

    let mut suffix = String::from(arch);
    if is_compact {
        suffix.push_str(".comp");
    }
    if has_blobs {
        suffix.push_str(".blobs");
    }
    suffix.push_str(".bin");

    let info = BuildInfo {
        filename: format!("geodb.{suffix}"),
        size_bytes: EMBEDDED_DB.len(),
        architecture: arch,
        features: Features {
            legacy_model: cfg!(feature = "legacy_model"),
            compact: is_compact,
            search_blobs: has_blobs,
        },
    };

    to_value(&info).unwrap_or(JsValue::NULL)
}

/// Finds the nearest cities to a given geographic coordinate.
///
/// This function performs a k-nearest neighbor (k-NN) search to find a specified
/// number of cities closest to the provided latitude and longitude.
///
/// # Arguments
///
/// * `lat` - The latitude of the search center, in decimal degrees.
/// * `lng` - The longitude of the search center, in decimal degrees.
/// * `count` - The maximum number of nearest cities to return.
///
/// # Returns
///
/// A `JsValue` containing a JSON array of `CityView` objects, sorted by
/// distance from the search point (closest first). Returns `JsValue::NULL` if the
/// database is not initialized.
#[wasm_bindgen]
pub fn find_nearest_cities(lat: f64, lng: f64, count: usize) -> JsValue {
    let out: Option<Vec<_>> = DB.get().map(|db| {
        db.find_nearest(lat, lng, count)
            .into_iter()
            .map(|(city, state, country)| CityView {
                country,
                state,
                city,
            })
            .collect()
    });
    to_value(&out).unwrap_or(JsValue::NULL)
}

/// Finds all cities within a specified radius from a given geographic coordinate.
///
/// This function performs a spatial search to identify cities located within a circular
/// area defined by a center point (latitude and longitude) and a radius in kilometers.
///
/// # Arguments
///
/// * `lat` - The latitude of the search center, in decimal degrees.
/// * `lng` - The longitude of the search center, in decimal degrees.
/// * `radius_km` - The search radius in kilometers.
///
/// # Returns
///
/// A `JsValue` containing a JSON array of `CityView` objects, where each object
/// represents a city found within the radius. Returns `JsValue::NULL` if the
/// database is not initialized.
#[wasm_bindgen]
pub fn find_cities_in_radius(lat: f64, lng: f64, radius_km: f64) -> JsValue {
    let out: Option<Vec<_>> = DB.get().map(|db| {
        // 1. Convert inputs to GeoID (Z-Order Curve)
        let geoid = geodb_core::spatial::generate_geoid(lat, lng);

        // 2. Search
        db.find_cities_in_radius_by_geoid(geoid, radius_km)
            .into_iter()
            .map(|(city, state, country)| CityView {
                country,
                state,
                city,
            })
            .collect()
    });
    to_value(&out).unwrap_or(JsValue::NULL)
}
