//! Location and distance from the stored 64-bit geoid alone.
//!
//! A geoid (see `geodb_core::spatial`) interleaves two 32-bit quantized axes
//! (Morton / Z-order): latitude in the odd bits, longitude in the even bits.
//! One latitude step is 180° / (2^32 - 1) ≈ 4.66 mm, one longitude step twice
//! that times cos(lat).
//!
//! The functions here are written so they port directly to a microcontroller:
//! nothing allocates, and [`distance_mm_fixed`] uses integer arithmetic only
//! (no FPU needed; a Q30 cosine table replaces `cos`). The float variants show
//! what an FPU with single precision (e.g. Cortex-M4F) or double precision
//! would compute.

/// Quantization range of each axis (`u32::MAX`, as used by `generate_geoid`).
const AXIS_MAX: f64 = 4_294_967_295.0;
/// Mean earth radius used throughout geodb (km).
const R_KM: f64 = 6371.0;
/// Millimetres per latitude step, scaled by 1e6: π·R / (2^32 - 1).
const LAT_STEP_MM_E6: u128 = 4_660_141;

// `COS_Q30` / `COS_STEPS_PER_DEG`: cos(0°..=90°) in Q30, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/cos_table.rs"));

/// Splits a geoid into its quantized (latitude, longitude) axes.
/// Branch-free "magic bits" deinterleave; same result as the library's loop.
pub fn split(code: u64) -> (u32, u32) {
    fn compact(mut x: u64) -> u32 {
        x &= 0x5555_5555_5555_5555;
        x = (x | (x >> 1)) & 0x3333_3333_3333_3333;
        x = (x | (x >> 2)) & 0x0f0f_0f0f_0f0f_0f0f;
        x = (x | (x >> 4)) & 0x00ff_00ff_00ff_00ff;
        x = (x | (x >> 8)) & 0x0000_ffff_0000_ffff;
        x = (x | (x >> 16)) & 0x0000_0000_ffff_ffff;
        x as u32
    }
    (compact(code >> 1), compact(code))
}

/// Location from a geoid in double precision.
pub fn decode_f64(code: u64) -> (f64, f64) {
    let (la, lo) = split(code);
    (
        la as f64 / AXIS_MAX * 180.0 - 90.0,
        lo as f64 / AXIS_MAX * 360.0 - 180.0,
    )
}

/// Location from a geoid in single precision (an FPU-only MCU).
pub fn decode_f32(code: u64) -> (f32, f32) {
    let (la, lo) = split(code);
    (
        la as f32 / AXIS_MAX as f32 * 180.0 - 90.0,
        lo as f32 / AXIS_MAX as f32 * 360.0 - 180.0,
    )
}

/// Keeps the 32 most significant bits (16 per axis), halving storage.
/// One cell is about 305 m (latitude) by 610 m·cos(lat).
pub fn truncate32(code: u64) -> u32 {
    (code >> 32) as u32
}

/// Expands a 32-bit geoid back to 64 bits at the centre of its cell.
pub fn expand32(short: u32) -> u64 {
    // The highest dropped bit of each axis (lat bit 31, lng bit 30) = half a cell.
    ((short as u64) << 32) | 0xC000_0000
}

/// Great-circle distance in km (double precision).
pub fn haversine_f64(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    let (p1, p2) = (lat1.to_radians(), lat2.to_radians());
    let dp = p2 - p1;
    let dl = (lon2 - lon1).to_radians();
    let a = (dp / 2.0).sin().powi(2) + p1.cos() * p2.cos() * (dl / 2.0).sin().powi(2);
    2.0 * R_KM * a.sqrt().min(1.0).asin()
}

/// Great-circle distance in km (single precision throughout).
pub fn haversine_f32(lat1: f32, lon1: f32, lat2: f32, lon2: f32) -> f32 {
    let (p1, p2) = (lat1.to_radians(), lat2.to_radians());
    let dp = p2 - p1;
    let dl = (lon2 - lon1).to_radians();
    let a = (dp / 2.0).sin().powi(2) + p1.cos() * p2.cos() * (dl / 2.0).sin().powi(2);
    2.0 * R_KM as f32 * a.sqrt().min(1.0).asin()
}

/// Signed axis deltas in latitude steps. Longitude wraps (antimeridian-safe).
fn deltas(a: u64, b: u64) -> (i64, i64, u64) {
    let (alat, alon) = split(a);
    let (blat, blon) = split(b);
    let dlat = alat as i64 - blat as i64;
    let dlon = alon.wrapping_sub(blon) as i32 as i64;
    (dlat, dlon, (alat as u64 + blat as u64) / 2)
}

/// Flat-earth distance in km from geoid deltas, f32 with `cos` of the mean latitude.
pub fn equirect_f32(a: u64, b: u64) -> f32 {
    let (dlat, dlon, mid) = deltas(a, b);
    let lat = (mid as f32 / AXIS_MAX as f32 * 180.0 - 90.0).to_radians();
    let step_km = (LAT_STEP_MM_E6 as f32) * 1e-12;
    let y = dlat as f32 * step_km;
    let x = dlon as f32 * 2.0 * step_km * lat.cos();
    (x * x + y * y).sqrt()
}

/// cos(|lat|) in Q30 from a quantized mean latitude, linearly interpolated.
fn cos_q30(mid_lat_units: u64) -> u64 {
    let abs = mid_lat_units.abs_diff(1 << 31);
    // |lat| in table steps, Q16 fixed point (2^32 units = 180°).
    let pos = (abs * 180 * COS_STEPS_PER_DEG) >> 16;
    let last = COS_Q30.len() - 2;
    let i = ((pos >> 16) as usize).min(last);
    let frac = pos.saturating_sub((i as u64) << 16).min(1 << 16);
    let (c0, c1) = (COS_Q30[i] as u64, COS_Q30[i + 1] as u64);
    c0 - (((c0 - c1) * frac) >> 16)
}

/// Flat-earth distance in millimetres using integer arithmetic only.
pub fn distance_mm_fixed(a: u64, b: u64) -> u64 {
    let (dlat, dlon, mid) = deltas(a, b);
    // Longitude steps are twice as long as latitude steps (at the equator).
    // |2·dlon| ≤ 2^32 and cos ≤ 2^30, so the product fits in i64.
    let x = (dlon * 2 * cos_q30(mid) as i64) >> 30;
    let (x, y) = (x.unsigned_abs(), dlat.unsigned_abs());
    // Squares fit in u64 below 2^31 steps (~10 000 km); beyond, use u128.
    let d = if x < 1 << 31 && y < 1 << 31 {
        (x * x + y * y).isqrt() as u128
    } else {
        (x as u128 * x as u128 + y as u128 * y as u128).isqrt()
    };
    (d * LAT_STEP_MM_E6 / 1_000_000) as u64
}

/// Squared flat-earth distance in latitude steps (integers only, no sqrt).
/// Returns `u64::MAX` for points more than ~10 000 km apart on either axis.
pub fn dist_sq_steps(a: u64, b: u64) -> u64 {
    let (dlat, dlon, mid) = deltas(a, b);
    let x = ((dlon * 2 * cos_q30(mid) as i64) >> 30).unsigned_abs();
    let y = dlat.unsigned_abs();
    if x >= 1 << 31 || y >= 1 << 31 {
        return u64::MAX;
    }
    x * x + y * y
}

/// Converts a radius in km into the squared step threshold for [`dist_sq_steps`].
pub fn radius_sq_steps(radius_km: f64) -> u64 {
    let steps = radius_km * 1e12 / LAT_STEP_MM_E6 as f64;
    (steps * steps).min(u64::MAX as f64 / 2.0) as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use geodb_core::spatial::{decode_geoid, generate_geoid};

    #[test]
    fn split_matches_library_decode() {
        for &(lat, lon) in &[
            (52.52, 13.405),
            (-33.87, 151.21),
            (0.0, -179.99),
            (89.9, 0.1),
        ] {
            let g = generate_geoid(lat, lon);
            let (a, b) = decode_f64(g);
            let (c, d) = decode_geoid(g);
            assert!((a - c).abs() < 1e-12 && (b - d).abs() < 1e-12);
        }
    }

    #[test]
    fn truncated_cell_centre_within_half_cell() {
        let (lat, lon) = (48.137, 11.575);
        let g = expand32(truncate32(generate_geoid(lat, lon)));
        let (la, lo) = decode_f64(g);
        let err_m = haversine_f64(lat, lon, la, lo) * 1000.0;
        assert!(err_m < 400.0, "{err_m}");
    }

    #[test]
    fn fixed_point_close_to_haversine_locally() {
        let (a, b) = ((52.52, 13.405), (52.39, 13.064)); // Berlin – Potsdam
        let real = haversine_f64(a.0, a.1, b.0, b.1);
        let mm = distance_mm_fixed(generate_geoid(a.0, a.1), generate_geoid(b.0, b.1));
        let err_m = (mm as f64 / 1e6 - real).abs() * 1000.0;
        assert!(err_m < 0.5, "{err_m} m off over {real} km");
    }

    #[test]
    fn fixed_point_wraps_antimeridian() {
        let a = generate_geoid(-17.0, 179.9);
        let b = generate_geoid(-17.0, -179.9);
        let km = distance_mm_fixed(a, b) as f64 / 1e6;
        assert!((km - 21.3).abs() < 0.5, "{km}");
    }

    #[test]
    fn squared_steps_agree_with_millimetres() {
        let (a, b) = (generate_geoid(52.52, 13.405), generate_geoid(52.39, 13.064));
        let km = distance_mm_fixed(a, b) as f64 / 1e6;
        assert!(dist_sq_steps(a, b) <= radius_sq_steps(km + 0.001));
        assert!(dist_sq_steps(a, b) > radius_sq_steps(km - 0.001));
        assert_eq!(
            dist_sq_steps(generate_geoid(60.0, 0.0), generate_geoid(-60.0, 0.0)),
            u64::MAX
        );
    }

    #[test]
    fn cos_table_accuracy() {
        assert_eq!(cos_q30(1 << 31), 1 << 30);
        assert!(cos_q30(u32::MAX as u64) < 1 << 12);
        for deg in [0.3, 17.77, 45.0, 60.0, 71.05, 89.4] {
            let units = ((deg + 90.0) / 180.0 * AXIS_MAX) as u64;
            let c = cos_q30(units) as f64 / (1u64 << 30) as f64;
            let exact = f64::to_radians(deg).cos();
            assert!((c - exact).abs() < 1e-6, "{deg}: {c} vs {exact}");
        }
    }
}
