#!/usr/bin/env zsh
set -e

echo "============================================================"
echo "  geodb-rs FULL CLEAN BUILD (Rust → XCFramework → Flutter)"
echo "============================================================"

ROOT=$(pwd)
FFI_DIR="$ROOT/crates/geodb-ffi"
PLUGIN_DIR="$FFI_DIR/geodb_flutter"

# 1. Clean
echo "[1] Cleaning previous build artifacts…"
rm -rf "$FFI_DIR/generated"
rm -rf "$FFI_DIR/GeodbFfi.xcframework"
rm -rf "$PLUGIN_DIR"

# 2. Generate Bindings
echo "[2] Generating Swift bindings with uniffi-bindgen…"
cd "$FFI_DIR"
cargo run --bin uniffi-bindgen -- \
    generate src/geodb.udl \
    --language swift \
    --out-dir generated/swift

echo ""

# 3. Build Rust (Device)
echo "[3] Building Rust library for iOS device…"
cargo build --release --target aarch64-apple-ios

# 4. Build Rust (Simulator)
echo "[4] Building Rust library for iOS simulator…"
cargo build --release --target aarch64-apple-ios-sim

# 5. Create XCFramework
echo "[5] Creating XCFramework…"
# Note: We are statically linking the Rust lib.
xcodebuild -create-xcframework \
    -library ../../target/aarch64-apple-ios/release/libgeodb_ffi.a \
    -headers generated/swift \
    -library ../../target/aarch64-apple-ios-sim/release/libgeodb_ffi.a \
    -headers generated/swift \
    -output GeodbFfi.xcframework

# 6. Create Flutter Plugin
echo "[6] Creating fresh Flutter plugin…"
cd "$FFI_DIR"
# We don't delete PLUGIN_DIR here again because we just did in step 1?
# Actually, step 1 deleted it. But let's be safe.
if [ -d "$PLUGIN_DIR" ]; then rm -rf "$PLUGIN_DIR"; fi

flutter create --template=plugin --platforms=ios,android "$PLUGIN_DIR"

# 7. Install Artifacts
echo "[7] Installing XCFramework + Swift bindings into iOS plugin…"
mkdir -p "$PLUGIN_DIR/ios/Classes"

# Copy XCFramework
cp -R "$FFI_DIR/GeodbFfi.xcframework" "$PLUGIN_DIR/ios/"

# Copy Swift & C-Headers
# Ensure we copy headers to Classes so they are found by Podspec
cp "$FFI_DIR/generated/swift/"*.swift "$PLUGIN_DIR/ios/Classes/"
cp "$FFI_DIR/generated/swift/"*.h "$PLUGIN_DIR/ios/Classes/"
# We rename modulemap to module.map to be standard, or keep name and point podspec to it.
cp "$FFI_DIR/generated/swift/"*.modulemap "$PLUGIN_DIR/ios/Classes/module.modulemap"

# ------------------------------------------------------------------
# 8. Patch geodb_flutter.podspec
# ------------------------------------------------------------------
echo "[8] Patching geodb_flutter.podspec…"
PODSPEC="$PLUGIN_DIR/ios/geodb_flutter.podspec"

cat > "$PODSPEC" <<'EOF'
Pod::Spec.new do |s|
  s.name             = 'geodb_flutter'
  s.version          = '0.0.1'
  s.summary          = 'Flutter plugin for geodb-ffi'
  s.homepage         = 'https://github.com/holg/geodb-rs'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Trahe Consult <trahe@mac.com>' => '' }
  s.source           = { :path => '.' }

  # Swift glue generated by uniffi
  s.source_files        = 'Classes/**/*.swift'

  # C FFI module from uniffi: header + modulemap
  s.public_header_files = 'Classes/geodb_ffiFFI.h'
  s.module_map          = 'Classes/geodb_ffiFFI.modulemap'

  s.dependency 'Flutter'
  s.platform = :ios, '13.0'

  # Rust XCFramework (contains the compiled static libs)
  s.vendored_frameworks = 'GeodbFfi.xcframework'
  s.static_framework    = true
  s.swift_version       = '5.0'

  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'CLANG_ENABLE_MODULES' => 'YES',
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386'
  }
end
EOF
# 9. Recreate Example
echo "[9] Recreating example/ios completely for a clean build…"
rm -rf "$PLUGIN_DIR/example/ios"
cd "$PLUGIN_DIR/example"
flutter create .

# 10. Podfile
echo "[10] Writing minimal Podfile for example iOS app…"
cd "$PLUGIN_DIR/example/ios"

cat > Podfile <<'PODFILE'
platform :ios, '13.0'

# Disable analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path('../Flutter/podhelper', __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
PODFILE

# 11. Install
echo "[11] Installing Pods…"
# We need to ensure the Flutter dependencies are fetched before pod install
# flutter pub get is redundant if 'flutter create .' ran, but safe.
pod install --repo-update

echo ""
echo "============================================================"
echo "  BUILD COMPLETE 🎉"
echo "  XCFramework + Flutter plugin are fully rebuilt!"
echo "  Next steps:"
echo "     cd crates/geodb-ffi/geodb_flutter/example"
echo "     flutter run"
echo "============================================================"